territory:
  code: GY
  name: Guernsey
source_priority:
- guernsey_gov_arcgis
- guernsey_cadastre_land_parcels
- digimap_guernsey
- osm_overpass
- osm_geofabrik
validation:
  bbox_wgs84:
    min_lat: 49.4
    max_lat: 49.55
    min_lon: -2.7
    max_lon: -2.45
arcgis:
  enabled: false
  services:
  - name: guernsey_gov_arcgis
    service_url: https://cadastreonline.digimap.gg/arcgis/rest/services/StatesOfGuernsey/CafMapOL/MapServer
    layer_ids:
    - 0
    query_where: 1=1
    id_chunk_size: 500
    out_fields: '*'
    expects_authoritative: true
    source_label: authoritative
  - name: guernsey_cadastre_land_parcels
    service_url: https://gps.digimap.gg/arcgis/rest/services/StatesOfGuernsey/CadastreTRPOL/MapServer
    layer_ids:
    - 2
    query_where: 1=1
    id_chunk_size: 500
    out_fields: OBJECTID,POSTCODE
    return_geometry: false
    expects_authoritative: true
    source_label: authoritative
overpass:
  enabled: false
  endpoint: https://overpass-api.de/api/interpreter
  timeout_seconds: 180
  area_strategy: bbox
  bbox:
  - 49.4
  - -2.7
  - 49.55
  - -2.45
geofabrik:
  enabled: false
  input_path: ''
  pbf_path: ''
  download_url: ''
fields:
  postcode_candidates:
  - postcode
  - POSTCODE
  - addr_postcode
  - addr:postcode
  - PostCode
  - Postcode
  lat_candidates:
  - lat
  - LATITUDE
  - y
  lon_candidates:
  - lon
  - LONGITUDE
  - x
  geometry_field: geometry
crs:
  default_epsg: 4326
  authoritative_epsg_hint_by_source:
    guernsey_gov_arcgis: 4326
    guernsey_cadastre_land_parcels: 3108
scoring_profile: default
output:
  canonical_filename: guernsey.csv
  onspd_filename: guernsey_onspd.csv
