territory:
  code: JE
  name: Jersey
source_priority:
- jersey_gov_arcgis
- jersey_jsearch_postcode_centroids
- digimap_jersey
- osm_overpass
- osm_geofabrik
validation:
  bbox_wgs84:
    min_lat: 49.15
    max_lat: 49.31
    min_lon: -2.3
    max_lon: -1.95
arcgis:
  enabled: false
  services:
  - name: jersey_gov_arcgis
    service_url: https://gps.digimap.gg/arcgis/rest/services/StatesOfJersey/JerseyPlanning/MapServer
    layer_ids:
    - 0
    query_where: 1=1
    id_chunk_size: 500
    out_fields: '*'
    expects_authoritative: true
    source_label: authoritative
  - name: jersey_jsearch_postcode_centroids
    service_url: https://gps.digimap.gg/arcgis/rest/services/JSearch/MapServer
    layer_ids:
    - 0
    query_where: 1=1
    id_chunk_size: 500
    out_fields: OBJECTID,Postcode
    expects_authoritative: true
    source_label: authoritative
overpass:
  enabled: false
  endpoint: https://overpass-api.de/api/interpreter
  timeout_seconds: 180
  area_strategy: bbox
  bbox:
  - 49.15
  - -2.3
  - 49.31
  - -1.95
geofabrik:
  enabled: false
  input_path: ''
  pbf_path: ''
  download_url: ''
fields:
  postcode_candidates:
  - postcode
  - POSTCODE
  - addr_postcode
  - addr:postcode
  - PostCode
  - Postcode
  lat_candidates:
  - lat
  - LATITUDE
  - y
  lon_candidates:
  - lon
  - LONGITUDE
  - x
  geometry_field: geometry
crs:
  default_epsg: 4326
  authoritative_epsg_hint_by_source:
    jersey_gov_arcgis: 4326
    jersey_jsearch_postcode_centroids: 3109
scoring_profile: default
output:
  canonical_filename: jersey.csv
  onspd_filename: jersey_onspd.csv
